name: Java CI with Maven
permissions:
  contents: read
  pull-requests: write
  statuses: write
on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode package --file pom.xml -DskipTests
